package dao;

import entity.Sensor;
import entity.SensorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SensorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int countByExample(SensorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int deleteByExample(SensorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int insert(Sensor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int insertSelective(Sensor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    List<Sensor> selectByExample(SensorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    Sensor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Sensor record, @Param("example") SensorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Sensor record, @Param("example") SensorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sensor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sensor record);
}