package entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SensorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sensor
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sensor
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sensor
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public SensorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sensor
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialIsNull() {
            addCriterion("demodulator_serial is null");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialIsNotNull() {
            addCriterion("demodulator_serial is not null");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialEqualTo(String value) {
            addCriterion("demodulator_serial =", value, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialNotEqualTo(String value) {
            addCriterion("demodulator_serial <>", value, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialGreaterThan(String value) {
            addCriterion("demodulator_serial >", value, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialGreaterThanOrEqualTo(String value) {
            addCriterion("demodulator_serial >=", value, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialLessThan(String value) {
            addCriterion("demodulator_serial <", value, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialLessThanOrEqualTo(String value) {
            addCriterion("demodulator_serial <=", value, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialLike(String value) {
            addCriterion("demodulator_serial like", value, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialNotLike(String value) {
            addCriterion("demodulator_serial not like", value, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialIn(List<String> values) {
            addCriterion("demodulator_serial in", values, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialNotIn(List<String> values) {
            addCriterion("demodulator_serial not in", values, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialBetween(String value1, String value2) {
            addCriterion("demodulator_serial between", value1, value2, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andDemodulatorSerialNotBetween(String value1, String value2) {
            addCriterion("demodulator_serial not between", value1, value2, "demodulatorSerial");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("channel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(Integer value) {
            addCriterion("channel_id =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(Integer value) {
            addCriterion("channel_id <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(Integer value) {
            addCriterion("channel_id >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_id >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(Integer value) {
            addCriterion("channel_id <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("channel_id <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<Integer> values) {
            addCriterion("channel_id in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<Integer> values) {
            addCriterion("channel_id not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("channel_id between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_id not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdIsNull() {
            addCriterion("bridge_id is null");
            return (Criteria) this;
        }

        public Criteria andBridgeIdIsNotNull() {
            addCriterion("bridge_id is not null");
            return (Criteria) this;
        }

        public Criteria andBridgeIdEqualTo(Integer value) {
            addCriterion("bridge_id =", value, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdNotEqualTo(Integer value) {
            addCriterion("bridge_id <>", value, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdGreaterThan(Integer value) {
            addCriterion("bridge_id >", value, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bridge_id >=", value, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdLessThan(Integer value) {
            addCriterion("bridge_id <", value, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdLessThanOrEqualTo(Integer value) {
            addCriterion("bridge_id <=", value, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdIn(List<Integer> values) {
            addCriterion("bridge_id in", values, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdNotIn(List<Integer> values) {
            addCriterion("bridge_id not in", values, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdBetween(Integer value1, Integer value2) {
            addCriterion("bridge_id between", value1, value2, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andBridgeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bridge_id not between", value1, value2, "bridgeId");
            return (Criteria) this;
        }

        public Criteria andLaneIdIsNull() {
            addCriterion("lane_id is null");
            return (Criteria) this;
        }

        public Criteria andLaneIdIsNotNull() {
            addCriterion("lane_id is not null");
            return (Criteria) this;
        }

        public Criteria andLaneIdEqualTo(Integer value) {
            addCriterion("lane_id =", value, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdNotEqualTo(Integer value) {
            addCriterion("lane_id <>", value, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdGreaterThan(Integer value) {
            addCriterion("lane_id >", value, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("lane_id >=", value, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdLessThan(Integer value) {
            addCriterion("lane_id <", value, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdLessThanOrEqualTo(Integer value) {
            addCriterion("lane_id <=", value, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdIn(List<Integer> values) {
            addCriterion("lane_id in", values, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdNotIn(List<Integer> values) {
            addCriterion("lane_id not in", values, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdBetween(Integer value1, Integer value2) {
            addCriterion("lane_id between", value1, value2, "laneId");
            return (Criteria) this;
        }

        public Criteria andLaneIdNotBetween(Integer value1, Integer value2) {
            addCriterion("lane_id not between", value1, value2, "laneId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andVendorIsNull() {
            addCriterion("vendor is null");
            return (Criteria) this;
        }

        public Criteria andVendorIsNotNull() {
            addCriterion("vendor is not null");
            return (Criteria) this;
        }

        public Criteria andVendorEqualTo(String value) {
            addCriterion("vendor =", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotEqualTo(String value) {
            addCriterion("vendor <>", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorGreaterThan(String value) {
            addCriterion("vendor >", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorGreaterThanOrEqualTo(String value) {
            addCriterion("vendor >=", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLessThan(String value) {
            addCriterion("vendor <", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLessThanOrEqualTo(String value) {
            addCriterion("vendor <=", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLike(String value) {
            addCriterion("vendor like", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotLike(String value) {
            addCriterion("vendor not like", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorIn(List<String> values) {
            addCriterion("vendor in", values, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotIn(List<String> values) {
            addCriterion("vendor not in", values, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorBetween(String value1, String value2) {
            addCriterion("vendor between", value1, value2, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotBetween(String value1, String value2) {
            addCriterion("vendor not between", value1, value2, "vendor");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("longitude like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("longitude not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("latitude like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("latitude not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andWaveLenIsNull() {
            addCriterion("wave_len is null");
            return (Criteria) this;
        }

        public Criteria andWaveLenIsNotNull() {
            addCriterion("wave_len is not null");
            return (Criteria) this;
        }

        public Criteria andWaveLenEqualTo(Double value) {
            addCriterion("wave_len =", value, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenNotEqualTo(Double value) {
            addCriterion("wave_len <>", value, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenGreaterThan(Double value) {
            addCriterion("wave_len >", value, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenGreaterThanOrEqualTo(Double value) {
            addCriterion("wave_len >=", value, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenLessThan(Double value) {
            addCriterion("wave_len <", value, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenLessThanOrEqualTo(Double value) {
            addCriterion("wave_len <=", value, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenIn(List<Double> values) {
            addCriterion("wave_len in", values, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenNotIn(List<Double> values) {
            addCriterion("wave_len not in", values, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenBetween(Double value1, Double value2) {
            addCriterion("wave_len between", value1, value2, "waveLen");
            return (Criteria) this;
        }

        public Criteria andWaveLenNotBetween(Double value1, Double value2) {
            addCriterion("wave_len not between", value1, value2, "waveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenIsNull() {
            addCriterion("max_wave_len is null");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenIsNotNull() {
            addCriterion("max_wave_len is not null");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenEqualTo(Double value) {
            addCriterion("max_wave_len =", value, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenNotEqualTo(Double value) {
            addCriterion("max_wave_len <>", value, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenGreaterThan(Double value) {
            addCriterion("max_wave_len >", value, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenGreaterThanOrEqualTo(Double value) {
            addCriterion("max_wave_len >=", value, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenLessThan(Double value) {
            addCriterion("max_wave_len <", value, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenLessThanOrEqualTo(Double value) {
            addCriterion("max_wave_len <=", value, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenIn(List<Double> values) {
            addCriterion("max_wave_len in", values, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenNotIn(List<Double> values) {
            addCriterion("max_wave_len not in", values, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenBetween(Double value1, Double value2) {
            addCriterion("max_wave_len between", value1, value2, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMaxWaveLenNotBetween(Double value1, Double value2) {
            addCriterion("max_wave_len not between", value1, value2, "maxWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenIsNull() {
            addCriterion("min_wave_len is null");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenIsNotNull() {
            addCriterion("min_wave_len is not null");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenEqualTo(Double value) {
            addCriterion("min_wave_len =", value, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenNotEqualTo(Double value) {
            addCriterion("min_wave_len <>", value, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenGreaterThan(Double value) {
            addCriterion("min_wave_len >", value, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenGreaterThanOrEqualTo(Double value) {
            addCriterion("min_wave_len >=", value, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenLessThan(Double value) {
            addCriterion("min_wave_len <", value, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenLessThanOrEqualTo(Double value) {
            addCriterion("min_wave_len <=", value, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenIn(List<Double> values) {
            addCriterion("min_wave_len in", values, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenNotIn(List<Double> values) {
            addCriterion("min_wave_len not in", values, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenBetween(Double value1, Double value2) {
            addCriterion("min_wave_len between", value1, value2, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andMinWaveLenNotBetween(Double value1, Double value2) {
            addCriterion("min_wave_len not between", value1, value2, "minWaveLen");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeIsNull() {
            addCriterion("compensation_code is null");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeIsNotNull() {
            addCriterion("compensation_code is not null");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeEqualTo(String value) {
            addCriterion("compensation_code =", value, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeNotEqualTo(String value) {
            addCriterion("compensation_code <>", value, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeGreaterThan(String value) {
            addCriterion("compensation_code >", value, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("compensation_code >=", value, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeLessThan(String value) {
            addCriterion("compensation_code <", value, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeLessThanOrEqualTo(String value) {
            addCriterion("compensation_code <=", value, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeLike(String value) {
            addCriterion("compensation_code like", value, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeNotLike(String value) {
            addCriterion("compensation_code not like", value, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeIn(List<String> values) {
            addCriterion("compensation_code in", values, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeNotIn(List<String> values) {
            addCriterion("compensation_code not in", values, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeBetween(String value1, String value2) {
            addCriterion("compensation_code between", value1, value2, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andCompensationCodeNotBetween(String value1, String value2) {
            addCriterion("compensation_code not between", value1, value2, "compensationCode");
            return (Criteria) this;
        }

        public Criteria andKIsNull() {
            addCriterion("k is null");
            return (Criteria) this;
        }

        public Criteria andKIsNotNull() {
            addCriterion("k is not null");
            return (Criteria) this;
        }

        public Criteria andKEqualTo(Double value) {
            addCriterion("k =", value, "k");
            return (Criteria) this;
        }

        public Criteria andKNotEqualTo(Double value) {
            addCriterion("k <>", value, "k");
            return (Criteria) this;
        }

        public Criteria andKGreaterThan(Double value) {
            addCriterion("k >", value, "k");
            return (Criteria) this;
        }

        public Criteria andKGreaterThanOrEqualTo(Double value) {
            addCriterion("k >=", value, "k");
            return (Criteria) this;
        }

        public Criteria andKLessThan(Double value) {
            addCriterion("k <", value, "k");
            return (Criteria) this;
        }

        public Criteria andKLessThanOrEqualTo(Double value) {
            addCriterion("k <=", value, "k");
            return (Criteria) this;
        }

        public Criteria andKIn(List<Double> values) {
            addCriterion("k in", values, "k");
            return (Criteria) this;
        }

        public Criteria andKNotIn(List<Double> values) {
            addCriterion("k not in", values, "k");
            return (Criteria) this;
        }

        public Criteria andKBetween(Double value1, Double value2) {
            addCriterion("k between", value1, value2, "k");
            return (Criteria) this;
        }

        public Criteria andKNotBetween(Double value1, Double value2) {
            addCriterion("k not between", value1, value2, "k");
            return (Criteria) this;
        }

        public Criteria andBIsNull() {
            addCriterion("b is null");
            return (Criteria) this;
        }

        public Criteria andBIsNotNull() {
            addCriterion("b is not null");
            return (Criteria) this;
        }

        public Criteria andBEqualTo(Double value) {
            addCriterion("b =", value, "b");
            return (Criteria) this;
        }

        public Criteria andBNotEqualTo(Double value) {
            addCriterion("b <>", value, "b");
            return (Criteria) this;
        }

        public Criteria andBGreaterThan(Double value) {
            addCriterion("b >", value, "b");
            return (Criteria) this;
        }

        public Criteria andBGreaterThanOrEqualTo(Double value) {
            addCriterion("b >=", value, "b");
            return (Criteria) this;
        }

        public Criteria andBLessThan(Double value) {
            addCriterion("b <", value, "b");
            return (Criteria) this;
        }

        public Criteria andBLessThanOrEqualTo(Double value) {
            addCriterion("b <=", value, "b");
            return (Criteria) this;
        }

        public Criteria andBIn(List<Double> values) {
            addCriterion("b in", values, "b");
            return (Criteria) this;
        }

        public Criteria andBNotIn(List<Double> values) {
            addCriterion("b not in", values, "b");
            return (Criteria) this;
        }

        public Criteria andBBetween(Double value1, Double value2) {
            addCriterion("b between", value1, value2, "b");
            return (Criteria) this;
        }

        public Criteria andBNotBetween(Double value1, Double value2) {
            addCriterion("b not between", value1, value2, "b");
            return (Criteria) this;
        }

        public Criteria andOrdIsNull() {
            addCriterion("ord is null");
            return (Criteria) this;
        }

        public Criteria andOrdIsNotNull() {
            addCriterion("ord is not null");
            return (Criteria) this;
        }

        public Criteria andOrdEqualTo(Integer value) {
            addCriterion("ord =", value, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdNotEqualTo(Integer value) {
            addCriterion("ord <>", value, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdGreaterThan(Integer value) {
            addCriterion("ord >", value, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ord >=", value, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdLessThan(Integer value) {
            addCriterion("ord <", value, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdLessThanOrEqualTo(Integer value) {
            addCriterion("ord <=", value, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdIn(List<Integer> values) {
            addCriterion("ord in", values, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdNotIn(List<Integer> values) {
            addCriterion("ord not in", values, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdBetween(Integer value1, Integer value2) {
            addCriterion("ord between", value1, value2, "ord");
            return (Criteria) this;
        }

        public Criteria andOrdNotBetween(Integer value1, Integer value2) {
            addCriterion("ord not between", value1, value2, "ord");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceIsNull() {
            addCriterion("next_device_distance is null");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceIsNotNull() {
            addCriterion("next_device_distance is not null");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceEqualTo(Double value) {
            addCriterion("next_device_distance =", value, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceNotEqualTo(Double value) {
            addCriterion("next_device_distance <>", value, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceGreaterThan(Double value) {
            addCriterion("next_device_distance >", value, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceGreaterThanOrEqualTo(Double value) {
            addCriterion("next_device_distance >=", value, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceLessThan(Double value) {
            addCriterion("next_device_distance <", value, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceLessThanOrEqualTo(Double value) {
            addCriterion("next_device_distance <=", value, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceIn(List<Double> values) {
            addCriterion("next_device_distance in", values, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceNotIn(List<Double> values) {
            addCriterion("next_device_distance not in", values, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceBetween(Double value1, Double value2) {
            addCriterion("next_device_distance between", value1, value2, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andNextDeviceDistanceNotBetween(Double value1, Double value2) {
            addCriterion("next_device_distance not between", value1, value2, "nextDeviceDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceIsNull() {
            addCriterion("bridge_head_distance is null");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceIsNotNull() {
            addCriterion("bridge_head_distance is not null");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceEqualTo(Double value) {
            addCriterion("bridge_head_distance =", value, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceNotEqualTo(Double value) {
            addCriterion("bridge_head_distance <>", value, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceGreaterThan(Double value) {
            addCriterion("bridge_head_distance >", value, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceGreaterThanOrEqualTo(Double value) {
            addCriterion("bridge_head_distance >=", value, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceLessThan(Double value) {
            addCriterion("bridge_head_distance <", value, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceLessThanOrEqualTo(Double value) {
            addCriterion("bridge_head_distance <=", value, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceIn(List<Double> values) {
            addCriterion("bridge_head_distance in", values, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceNotIn(List<Double> values) {
            addCriterion("bridge_head_distance not in", values, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceBetween(Double value1, Double value2) {
            addCriterion("bridge_head_distance between", value1, value2, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeHeadDistanceNotBetween(Double value1, Double value2) {
            addCriterion("bridge_head_distance not between", value1, value2, "bridgeHeadDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceIsNull() {
            addCriterion("bridge_tail_distance is null");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceIsNotNull() {
            addCriterion("bridge_tail_distance is not null");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceEqualTo(Double value) {
            addCriterion("bridge_tail_distance =", value, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceNotEqualTo(Double value) {
            addCriterion("bridge_tail_distance <>", value, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceGreaterThan(Double value) {
            addCriterion("bridge_tail_distance >", value, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceGreaterThanOrEqualTo(Double value) {
            addCriterion("bridge_tail_distance >=", value, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceLessThan(Double value) {
            addCriterion("bridge_tail_distance <", value, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceLessThanOrEqualTo(Double value) {
            addCriterion("bridge_tail_distance <=", value, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceIn(List<Double> values) {
            addCriterion("bridge_tail_distance in", values, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceNotIn(List<Double> values) {
            addCriterion("bridge_tail_distance not in", values, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceBetween(Double value1, Double value2) {
            addCriterion("bridge_tail_distance between", value1, value2, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andBridgeTailDistanceNotBetween(Double value1, Double value2) {
            addCriterion("bridge_tail_distance not between", value1, value2, "bridgeTailDistance");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterAIsNull() {
            addCriterion("areamethod_parameter_a is null");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterAIsNotNull() {
            addCriterion("areamethod_parameter_a is not null");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterAEqualTo(Double value) {
            addCriterion("areamethod_parameter_a =", value, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterANotEqualTo(Double value) {
            addCriterion("areamethod_parameter_a <>", value, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterAGreaterThan(Double value) {
            addCriterion("areamethod_parameter_a >", value, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterAGreaterThanOrEqualTo(Double value) {
            addCriterion("areamethod_parameter_a >=", value, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterALessThan(Double value) {
            addCriterion("areamethod_parameter_a <", value, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterALessThanOrEqualTo(Double value) {
            addCriterion("areamethod_parameter_a <=", value, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterAIn(List<Double> values) {
            addCriterion("areamethod_parameter_a in", values, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterANotIn(List<Double> values) {
            addCriterion("areamethod_parameter_a not in", values, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterABetween(Double value1, Double value2) {
            addCriterion("areamethod_parameter_a between", value1, value2, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterANotBetween(Double value1, Double value2) {
            addCriterion("areamethod_parameter_a not between", value1, value2, "areamethodParameterA");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBIsNull() {
            addCriterion("areamethod_parameter_b is null");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBIsNotNull() {
            addCriterion("areamethod_parameter_b is not null");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBEqualTo(Double value) {
            addCriterion("areamethod_parameter_b =", value, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBNotEqualTo(Double value) {
            addCriterion("areamethod_parameter_b <>", value, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBGreaterThan(Double value) {
            addCriterion("areamethod_parameter_b >", value, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBGreaterThanOrEqualTo(Double value) {
            addCriterion("areamethod_parameter_b >=", value, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBLessThan(Double value) {
            addCriterion("areamethod_parameter_b <", value, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBLessThanOrEqualTo(Double value) {
            addCriterion("areamethod_parameter_b <=", value, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBIn(List<Double> values) {
            addCriterion("areamethod_parameter_b in", values, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBNotIn(List<Double> values) {
            addCriterion("areamethod_parameter_b not in", values, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBBetween(Double value1, Double value2) {
            addCriterion("areamethod_parameter_b between", value1, value2, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andAreamethodParameterBNotBetween(Double value1, Double value2) {
            addCriterion("areamethod_parameter_b not between", value1, value2, "areamethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterAIsNull() {
            addCriterion("peakmethod_parameter_a is null");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterAIsNotNull() {
            addCriterion("peakmethod_parameter_a is not null");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterAEqualTo(Double value) {
            addCriterion("peakmethod_parameter_a =", value, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterANotEqualTo(Double value) {
            addCriterion("peakmethod_parameter_a <>", value, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterAGreaterThan(Double value) {
            addCriterion("peakmethod_parameter_a >", value, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterAGreaterThanOrEqualTo(Double value) {
            addCriterion("peakmethod_parameter_a >=", value, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterALessThan(Double value) {
            addCriterion("peakmethod_parameter_a <", value, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterALessThanOrEqualTo(Double value) {
            addCriterion("peakmethod_parameter_a <=", value, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterAIn(List<Double> values) {
            addCriterion("peakmethod_parameter_a in", values, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterANotIn(List<Double> values) {
            addCriterion("peakmethod_parameter_a not in", values, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterABetween(Double value1, Double value2) {
            addCriterion("peakmethod_parameter_a between", value1, value2, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterANotBetween(Double value1, Double value2) {
            addCriterion("peakmethod_parameter_a not between", value1, value2, "peakmethodParameterA");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBIsNull() {
            addCriterion("peakmethod_parameter_b is null");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBIsNotNull() {
            addCriterion("peakmethod_parameter_b is not null");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBEqualTo(Double value) {
            addCriterion("peakmethod_parameter_b =", value, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBNotEqualTo(Double value) {
            addCriterion("peakmethod_parameter_b <>", value, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBGreaterThan(Double value) {
            addCriterion("peakmethod_parameter_b >", value, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBGreaterThanOrEqualTo(Double value) {
            addCriterion("peakmethod_parameter_b >=", value, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBLessThan(Double value) {
            addCriterion("peakmethod_parameter_b <", value, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBLessThanOrEqualTo(Double value) {
            addCriterion("peakmethod_parameter_b <=", value, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBIn(List<Double> values) {
            addCriterion("peakmethod_parameter_b in", values, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBNotIn(List<Double> values) {
            addCriterion("peakmethod_parameter_b not in", values, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBBetween(Double value1, Double value2) {
            addCriterion("peakmethod_parameter_b between", value1, value2, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andPeakmethodParameterBNotBetween(Double value1, Double value2) {
            addCriterion("peakmethod_parameter_b not between", value1, value2, "peakmethodParameterB");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterionForJDBCDate("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterionForJDBCDate("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterionForJDBCDate("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterionForJDBCDate("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterionForJDBCDate("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterionForJDBCDate("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sensor
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sensor
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}